version: "2"

services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    volumes:
      -  ./db:/project/db
    ports:
      - 80:80

  score_calculation:
    build:
      dockerfile: ./db/Dockerfile
      context: ./
    volumes:
      - ./db:/project/db

  dash:
    build:
      dockerfile: ./dash/Dockerfile
      context: ./
    volumes:
      - ./db:/project/db
    ports:
      - 8050:80
